In [1]:
import torch
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

x.shape, x.t(), x.t().shape

(torch.Size([2, 3]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

In [33]:
x = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
],
[
    [10,11,12],
    [13,14,15],
    [16,17,18]
]])
y = x.transpose(2,0)
x.shape, y, y.shape

(torch.Size([2, 3, 3]),
 tensor([[[ 1, 10],
          [ 4, 13],
          [ 7, 16]],
 
         [[ 2, 11],
          [ 5, 14],
          [ 8, 17]],
 
         [[ 3, 12],
          [ 6, 15],
          [ 9, 18]]]),
 torch.Size([3, 3, 2]))

In [31]:
x = torch.randn(2,3,4)
print(x.shape)
y = x.permute(0,2,1)
print(y.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])


In [34]:
x = torch.randn(1,3,1,5)
x

tensor([[[[-0.0857, -0.1977, -0.1299,  0.3311,  0.1965]],

         [[ 0.9477, -0.7602, -0.8623,  0.0598,  0.2400]],

         [[ 0.8600, -0.9129,  1.0713, -0.2771,  0.7825]]]])

In [36]:
y = x.squeeze()
x.shape, y.shape

(torch.Size([1, 3, 1, 5]), torch.Size([3, 5]))

In [37]:
y

tensor([[-0.0857, -0.1977, -0.1299,  0.3311,  0.1965],
        [ 0.9477, -0.7602, -0.8623,  0.0598,  0.2400],
        [ 0.8600, -0.9129,  1.0713, -0.2771,  0.7825]])

In [39]:
x = torch.tensor([1,2,3])
print(x.shape)
y = x.unsqueeze(0)
print(y.shape)
print(y)
z = x.unsqueeze(1)
print(z.shape)
print(z)

torch.Size([3])
torch.Size([1, 3])
tensor([[1, 2, 3]])
torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])
